### PR TITLE
Bump Graal js language to support Java 22

### LINKED ISSUE #23: Doesn't support Java 22
As reported in Clerk https://github.com/nextjournal/clerk/issues/642. 

* https://bugs.openjdk.org/browse/JDK-8316160?subTaskView=unresolved
* https://github.com/oracle/graal/pull/7510

### PR DESCRIPTION
**Pull request by zampino**
Specifically with truffle api library dropping `sun.misc.Unsafe` which is no longer present in Java 22: 

* https://github.com/oracle/graal/pull/7510
* https://bugs.openjdk.org/browse/JDK-8316160

Closes #23.

🚧 This will probably not be merged, as we'd lose support of Java 11. We're trying to drop Graal polyglot (#25) for the clj side of things.

### CODE REVIEW

**Comment by zampino** [comment]
With the latest graal truffle we get support for Java 22, but we need at least Java 17.

**Comment by AndreaCrotti** [comment]
Weirdly enough I get this error when I run tests, but my colleagues don't with the same version of JDK (temurin11).
I tried multiple versions but always the same, and even more weirdly if I start the repl and run the tests in the repl it all works fine.

But more importantly, why does this library even depend on graalvm? Is that necessary for just using it for Clojure?
I tried to exclude all the JS dependencies since I don't need it for clojurescript but it blows up if I do that.

**Comment by zampino** [comment]
> why does this library even depend on graalvm?  Is that necessary for just using it for Clojure?

Yes, it is. Strictly speaking, we're not depending on GraalVM, but we're using the graal polyglot _library_ to call the [markdown-it](https://github.com/markdown-it/markdown-it) tokenizer on the JVM (GraalVM or any else), this guarantees the same behaviour on both clj/s sides. We're probably dropping this approach in #25.

**Comment by AndreaCrotti** [comment]
Ah nice good to know it might not be needed anymore soon, thanks

**Comment by zampino** [comment]
Obsolete since #28.

**Pull request closed without merging**
